# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "sha256-g9IBuXYG98JCDcnM6Rq92ULqAWNIUFAJHqAwRAzdZ2I=";
    armv7l-linux = "sha256-mcRyBQmGI5WcUInGYtteq375zdT4dvzuy9CJr+JMLt8=";
    aarch64-linux = "sha256-6+g+a8bMwF5ML47OPN8QEAn1c+9fGqD/O/Fxv5dNo88=";
    x86_64-darwin = "sha256-BUh4T4M12Rz0Z30VkhHCNJcUwiQdQ5W0SMznpAk3S4U=";
    aarch64-darwin = "sha256-84Diq8sXZ0fi5BnVuecHZs8BeK18QIKTzA76KqvXtlc=";
  };

  urlMap = {
    x86_64-linux = "https://github.com/purpleclay/nsv/releases/download/v0.10.2/nsv_0.10.2_linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/purpleclay/nsv/releases/download/v0.10.2/nsv_0.10.2_linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/purpleclay/nsv/releases/download/v0.10.2/nsv_0.10.2_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/purpleclay/nsv/releases/download/v0.10.2/nsv_0.10.2_darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/purpleclay/nsv/releases/download/v0.10.2/nsv_0.10.2_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "nsv";
  version = "0.10.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./nsv $out/bin/nsv
  '';
  postInstall = ''
    installShellCompletion --cmd nsv \
    --bash <($out/bin/nsv completion bash) \
    --fish <($out/bin/nsv completion fish) \
    --zsh <($out/bin/nsv completion zsh)
  '';

  system = system;

  meta = {
    description = "A convention-based semantic versioning tool that leans on the power of conventional commits to make versioning your software a breeze!";
    homepage = "https://github.com/purpleclay/nsv";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
