# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1pvbl2ykmnsy2iwp5y656hd7gc4jr3hxrf3njcgb63zpqs71zi83";
    armv7l-linux = "1jn91lisr80n8pjf9y0ckzw3ivq4gqga7z394a4j0yzdrqsi6si8";
    aarch64-linux = "1mfs1ccm0njkr3cfripjd4k2l5bzk3g7z1sh7a9kw8cdshswkifm";
    x86_64-darwin = "0jh49x3sj75bbn16qv085d44j7ngdqjs7q2bi2x2xvnqsbawkhmv";
    aarch64-darwin = "1i77mwd49xwqflx7rnckm7sbcwn8jr9sf6mq9aqc628pfmzn31h8";
  };

  urlMap = {
    x86_64-linux = "https://github.com/purpleclay/nsv/releases/download/v0.11.0/nsv_0.11.0_linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/purpleclay/nsv/releases/download/v0.11.0/nsv_0.11.0_linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/purpleclay/nsv/releases/download/v0.11.0/nsv_0.11.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/purpleclay/nsv/releases/download/v0.11.0/nsv_0.11.0_darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/purpleclay/nsv/releases/download/v0.11.0/nsv_0.11.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "nsv";
  version = "0.11.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./nsv $out/bin/nsv
    installManPage ./manpages/nsv.1.gz
  '';
  postInstall = ''
    installShellCompletion --cmd nsv \
    --bash <($out/bin/nsv completion bash) \
    --fish <($out/bin/nsv completion fish) \
    --zsh <($out/bin/nsv completion zsh)
  '';

  system = system;

  meta = {
    description = "A convention-based semantic versioning tool that leans on the power of conventional commits to make versioning your software a breeze!";
    homepage = "https://github.com/purpleclay/nsv";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
