# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "15x04a87szcbs0ck2xpmwblyng72ghvakaxmdm1dai2jk0ij01gj";
    armv7l-linux = "08shzv5cyna2c838f8n6x0ncb9kh429d5xxqcyzp6qmhkzdrw33l";
    aarch64-linux = "1j8xv6qfms1j4631h4yig4c15nkiakcx3cf41vwj3jyyydkdd54v";
    x86_64-darwin = "0n4lcfsijznjrqkz33qwhbxv4ydiz3jdw3qy3y0f5w8gi6pqkfn8";
    aarch64-darwin = "0ivxmyfibjxcv08n47y369gfa7gah999b4xvy3dx7fa6wncjdv2n";
  };

  urlMap = {
    x86_64-linux = "https://github.com/purpleclay/nsv/releases/download/v0.12.0/nsv_0.12.0_linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/purpleclay/nsv/releases/download/v0.12.0/nsv_0.12.0_linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/purpleclay/nsv/releases/download/v0.12.0/nsv_0.12.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/purpleclay/nsv/releases/download/v0.12.0/nsv_0.12.0_darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/purpleclay/nsv/releases/download/v0.12.0/nsv_0.12.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "nsv";
  version = "0.12.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./nsv $out/bin/nsv
    installManPage ./manpages/nsv.1.gz
  '';
  postInstall = ''
    installShellCompletion --cmd nsv \
    --bash <($out/bin/nsv completion bash) \
    --fish <($out/bin/nsv completion fish) \
    --zsh <($out/bin/nsv completion zsh)
  '';

  system = system;

  meta = {
    description = "A convention-based semantic versioning tool that leans on the power of conventional commits to make versioning your software a breeze!";
    homepage = "https://github.com/purpleclay/nsv";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
